# @package deploy.instance_type

name: 8c32m

# Storage-related vars
disk_device: /dev/sda
disk_partition: /dev/sda
disk_mount_point: /datadrive/data
disk_backup_mount_point: /datadrive/data/backup
mem_backup_mount_point: /datadrive/data/shm/backup

# Container isolation / restriction vars
cpuset_cpus_driver: 0-7
cpuset_cpus_workload: 0-7
mem_limit_driver: 8G
mem_limit_workload: 24G
shm_size_driver: 8G  # typically, >30% of mem limit
